version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"

python:
    install:
        - docs/RTD/requirements.txt

sphinx:
    configuration: docs/RTD/conf.py

submodules:
    exclude: all

formats:
    - htmlzip
    - pdf
