# version 1.0 HIPRFISR
version: 1
disable_existing_loggers: False
formatters:
    hiprfisrfmt:
        format: '%(asctime)s - %(name)s: [%(levelname)s] %(message)s'
        datefmt: '%m/%d/%Y %I:%M:%S %p'


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: hiprfisrfmt
        stream: ext://sys.stdout

    #set file handler for 5 backup log files of ~100MB each max
    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: hiprfisrfmt
        filename: Logs/event.log
        maxBytes: 10000000                
        backupCount: 5
    

root:
    level: DEBUG
    handlers: [console,file]

fissure:
    level: DEBUG
    handlers: [console, file]

fissure.dashboard:
    level: DEBUG
    handlers: [console, file]

fissure.hiprfisr:
    level: DEBUG
    handlers: [console, file]

fissure.pd:
    level: DEBUG
    handlers: [console, file]

fissure.tsi:
    level: DEBUG
    handlers: [console, file]

fissure.sensor_node:
    level: DEBUG
    handlers: [console, file]

fissure.test:
    level: DEBUG
    handlers: [console, file]
